
import React from 'react';
import { 
  LayoutDashboard, 
  Smartphone, 
  MessageSquare, 
  BarChart3, 
  Settings, 
  Bell, 
  Search, 
  Plus, 
  MoreVertical, 
  CheckCircle2,
  AlertCircle,
  Clock,
  Send,
  Signal,
  Battery,
  Wifi,
  Menu,
  X,
  LogOut,
  User,
  ChevronDown,
  ChevronRight,
  Server,
  CreditCard,
  Shield,
  Sliders,
  Router,
  FileText,
  Globe,
  Cpu,
  Layers,
  Share2,
  Cable,
  Activity,
  Barcode,
  Radio,
  RefreshCw,
  Power,
  Play,
  Pause,
  MoreHorizontal,
  Filter,
  Trash2,
  Save,
  Link,
  Upload,
  Download,
  RotateCcw,
  FileUp,
  FileDown,
  Lock,
  Check,
  AlertTriangle,
  Settings2,
  Database,
  ShieldCheck,
  Zap,
  /* Adding missing Info icon */
  Info,
  /* Adding missing Terminal icon */
  Terminal,
  /* Adding PlayCircle icon */
  PlayCircle,
  /* Adding missing ShieldAlert icon to resolve import errors */
  ShieldAlert,
  /* Adding missing Calendar icon to resolve import errors */
  Calendar,
  /* Adding missing Edit3 icon */
  Edit3,
  /* Adding missing icons for SimStatus component */
  List,
  XCircle,
  MinusCircle,
  UserMinus,
  PhoneCall,
  ArrowLeftRight,
  PlusCircle,
  Circle,
  /* Adding missing HelpCircle and ArrowRight icons */
  HelpCircle,
  ArrowRight,
  /* Adding missing Users and LayoutGrid icons */
  Users,
  LayoutGrid,
  /* Adding missing Mail icon */
  Mail
} from 'lucide-react';

export {
  LayoutDashboard, 
  Smartphone, 
  MessageSquare, 
  BarChart3, 
  Settings, 
  Bell, 
  Search, 
  Plus, 
  MoreVertical, 
  CheckCircle2,
  AlertCircle,
  Clock,
  Send,
  Signal,
  Battery,
  Wifi,
  Menu,
  X,
  LogOut,
  User,
  ChevronDown,
  ChevronRight,
  Server,
  CreditCard,
  Shield,
  Sliders,
  Router,
  FileText,
  Globe,
  Cpu,
  Layers,
  Share2,
  Cable,
  Activity,
  Barcode,
  Radio,
  RefreshCw,
  Power,
  Play,
  Pause,
  MoreHorizontal,
  Filter,
  Trash2,
  Save,
  Link,
  Upload,
  Download,
  RotateCcw,
  FileUp,
  FileDown,
  Lock,
  Check,
  AlertTriangle,
  Settings2,
  Database,
  ShieldCheck,
  Zap,
  /* Adding missing Info icon */
  Info,
  /* Adding missing Terminal icon */
  Terminal,
  /* Adding PlayCircle icon */
  PlayCircle,
  /* Adding missing ShieldAlert icon to resolve import errors */
  ShieldAlert,
  /* Adding missing Calendar icon to resolve import errors */
  Calendar,
  /* Adding missing Edit3 icon */
  Edit3,
  /* Adding missing icons for SimStatus component */
  List,
  XCircle,
  MinusCircle,
  UserMinus,
  PhoneCall,
  ArrowLeftRight,
  PlusCircle,
  Circle,
  /* Adding missing HelpCircle and ArrowRight icons */
  HelpCircle,
  ArrowRight,
  /* Adding missing Users and LayoutGrid icons */
  Users,
  LayoutGrid,
  /* Adding missing Mail icon */
  Mail
};